USE `balqan`;

INSERT
INTO items(imgs_srcs,
           NAME,
           intro,
           title,
           description,
           person_price,
           stock_quantity,
           days,
           min_persons,
           max_persons,
           category,
           STATUS)
VALUES ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/package/en/package-14.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "14 Day",
        "The 14-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "14",
        "1",
        "5",
        "package",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/package/en/package-10.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "10 Day",
        "The 10-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "10",
        "1",
        "5",
        "package",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/package/en/package-7.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "7 Day",
        "The 7-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "7",
        "1",
        "5",
        "package",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/package/en/package-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "4 Day",
        "The 4-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "4",
        "1",
        "5",
        "package",
        "available");
INSERT
INTO items(imgs_srcs,
           NAME,
           intro,
           title,
           description,
           day_price,
           stock_quantity,
           min_days,
           max_days,
           persons,
           category,
           STATUS)
VALUES ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/cars/car1.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Tesla",
        "The 14-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "1",
        "14",
        "3",
        "car",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/cars/car.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "BMW",
        "The 10-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "1",
        "10",
        "5",
        "car",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/cars/car3.jpeg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Porsche",
        "The 7-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "1",
        "7",
        "5",
        "car",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/cars/car4.avif https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Mercidies",
        "The 4-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "100",
        "4",
        "1",
        "2",
        "car",
        "available");
INSERT
INTO items(imgs_srcs,
           NAME,
           intro,
           title,
           description,
           person_price,
           day_price,
           stock_quantity,
           min_days,
           max_days,
           min_persons,
           max_persons,
           category,
           STATUS)
VALUES ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/hotels/holiday.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Holiday Hotel",
        "The 14-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "40",
        "100",
        "1",
        "14",
        "2",
        "10",
        "hotel",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/hotels/hotel2.png https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Hotel",
        "The 10-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "10",
        "16",
        "100",
        "1",
        "10",
        "1",
        "9",
        "hotel",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/hotels/hotel3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Hotel",
        "The 7-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "50",
        "25",
        "100",
        "1",
        "7",
        "2",
        "5",
        "hotel",
        "available"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/hotels/hotel4.jpeg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-10.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-9.webp https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-2.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-3.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-4.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-5.jpg https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/tourist-places/tourist-places-6.jpg",
        "Hotel",
        "The 4-day tourist days program includes visits to the cities of Sarajevo and ",
        "A tourist program in Bosnian",
        "One month of the tourism program for Bosnia: Accommodation in 4-star hotels with one month and two mobile SIM cards at reception, in addition to accommodation between cities and reception and farewell at airports. Its special monthly launch begins with a private driver to explore the most important tourist attractions of the current year. It is distinguished by its distinguished excellence with all the advantages provided to you The option can also be modified according to the customer's choice",
        "55",
        "50",
        "25",
        "1",
        "4",
        "1",
        "5",
        "hotel",
        "available");
INSERT INTO articles (img_src, category, country, title, description, img_desc, status, content)
VALUES ("https://www.hit-booker.com/wp-content/uploads/2022/02/327-3276102_bosnia-and-herzegovina-mostar.jpg",
        "cities", "Bosnia", "The important tourist cities", "For those seeking vital tourism info in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "{{{1. Sarajevo:}}}(((A city known for its historical sites and stunning natural landscapes, situated at the confluence of Eastern and Western civilizations. It boasts attractions like Gazi Husrev-beg Mosque, Sebilj Square, the National Museum, Latin Bridge, Kravice Waterfalls, and more.))){{{2. Mostar:}}} (((Described as one of the most beautiful cities in the Balkans, it overlooks the Nera River and is only 25 km away from the Adriatic Sea coast. Attractions include the Mohammed Bey's Mosque, Stari Most Bridge, Kravica Waterfalls, and the Old Bazaar.))){{{3. :}}} (((Located about 4 hours northwest of Sarajevo, it's renowned for its charming natural landscapes, including Una National Park with its beautiful river. Attractions include the Ostroac Castle, Una National Park, Captain's Tower, Fethija Mosque, Kantara Historical Museum, Martin Brod Waterfalls, and  Buk.))){{{4. Travnik:}}} (((Situated in the valley of the Lava River, just 90 km from Sarajevo, it's known for its beautiful nature suitable for leisure and sightseeing. Attractions include the Lava River, Old Town Travnik, Stari Grad Fortress, and other beautiful spots.))){{{Top 3 Tourist Attractions in Bosnia and Herzegovina:}}}{{{{1. Skakavac Waterfall:}}}} (((Located 12 km north of Sarajevo, it's one of the highest waterfalls in Bosnia and Herzegovina at 98 meters, offering breathtaking views of green mountains and cascading waterfalls.))){{{{2. Neretva River:}}}} (((Passing through Konjic, it's the largest river in the eastern part of the Adriatic Sea, known for its beautiful natural scenery spread along its banks.))){{{{3. Jahorina Mountain:}}}} (((Near the municipality of Pale and bordering Trebevi Mountain, it's part of the Dinaric Alps. With its highest peak reaching 1910 meters, it's ideal for skiing and was the venue for the 1984 Winter Olympics. Accessible from Sarajevo by bus.)))"),
       ("https://lll.ba/wp-content/uploads/2023/08/Old-Bridge-Stari-most-Unesco-Mostar-Bosnia-Herzegovina-lll.ba_-1.jpg",
        "tourism", "Bosnia", "An overview of tourism in Bosnia", "For those seeking vital tourism info in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "{{{Information about Bosnia and Herzegovina:}}}(((Bosnia and Herzegovina is characterized by its diverse attractions and tourist areas that attract tourists and visitors from different parts of the world to the extent that some websites describe it as one of the best tourist destinations in Europe due to its unique landmarks, charming nature, and affordable tourism prices compared to neighboring European countries.))){{{History of Bosnia and Herzegovina:}}}(((Bosnia is an ancient European country with a long history. It has enjoyed an important political and geographical status since the Middle Ages until the present day. It has been present on maps and known by its current name, Bosnia, for over 650 years, indicating its historical roots and antiquity.))){{{Location of Bosnia and Herzegovina:}}}(((The Republic of Bosnia and Herzegovina is located in the region known as the Balkans, situated in the southeastern part of Europe. Bosnia has a coastline on the Adriatic Sea, which is a branch of the Mediterranean Sea. The Adriatic Sea separates the Italian peninsula from the Balkan Peninsula, and the Dinaric Alps separate it from the Apennine Mountains.))){{{Weather in Bosnia and Herzegovina:}}} {{{{Bosnia is characterized by two main climates:}}}} {{{{{Continental or semi-continental climate:}}}}}(((The country experiences hot summers and cold winters, with snowfall. This climate is concentrated in the northern part of Bosnia and Herzegovina.))){{{{{Mediterranean climate:}}}}}(((This type of climate is evident in the southern part of Bosnia.)))"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/articles/articles-4.jpg",
        "Hotels", "Bosnia", "The best 3 hotels in Bosnia", "For those looking for the most important hotels in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "(((For those looking for the most important hotels in Bosnia, we present an overview of some hotels in Sarajevo:))) {{{Hollywood Hotel}}} (((Located 2 km from Sarajevo International Airport and near the Ferhadija Springs in Bosnia, a tributary of the Bosna River, Hollywood Hotel is situated in the Ilida area.))) (((It offers modern and spacious rooms with complimentary use of the indoor pool, sauna, and sports center.))) (((Hollywood Hotel features 18 conference and meeting rooms, 3 restaurants, and a supermarket is located just 100 meters from the hotel.))) {{{Malak Regency Hotel}}} (((Just 12 km from the capital Sarajevo, Malak Regency Hotel - a 5-star hotel - is located in the Ilida area with a charming view of the mountains.))) (((The hotel is only about 5 km away from Sarajevo International Airport.))) (((One of the distinguishing features of this hotel is that it does not serve alcoholic beverages.))) (((The hotel also features an indoor pool, sauna, fitness center, and a gift shop.))) (((Local and international cuisine is served at this hotel.))) {{{Radon Plaza Hotel}}} (((Radon Plaza Hotel is classified as a 5-star hotel and is distinguished by its proximity to Sarajevo Airport, just 2.8 km away.))) (((Its rooms are equipped with soundproofing systems, some of which are designated as suites for honeymooners.))) (((The hotel also includes a wellness center available for complimentary use.))) (((The hotel's restaurant, located on the 15th floor, offers panoramic views of the city and serves breakfast)))"),
       ("https://www.hit-booker.com/wp-content/uploads/2022/02/327-3276102_bosnia-and-herzegovina-mostar.jpg",
        "cities", "Bosnia", "The important tourist cities", "For those seeking vital tourism info in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "{{{1. Sarajevo:}}}(((A city known for its historical sites and stunning natural landscapes, situated at the confluence of Eastern and Western civilizations. It boasts attractions like Gazi Husrev-beg Mosque, Sebilj Square, the National Museum, Latin Bridge, Kravice Waterfalls, and more.))){{{2. Mostar:}}} (((Described as one of the most beautiful cities in the Balkans, it overlooks the Nera River and is only 25 km away from the Adriatic Sea coast. Attractions include the Mohammed Bey's Mosque, Stari Most Bridge, Kravica Waterfalls, and the Old Bazaar.))){{{3. :}}} (((Located about 4 hours northwest of Sarajevo, it's renowned for its charming natural landscapes, including Una National Park with its beautiful river. Attractions include the Ostroac Castle, Una National Park, Captain's Tower, Fethija Mosque, Kantara Historical Museum, Martin Brod Waterfalls, and  Buk.))){{{4. Travnik:}}} (((Situated in the valley of the Lava River, just 90 km from Sarajevo, it's known for its beautiful nature suitable for leisure and sightseeing. Attractions include the Lava River, Old Town Travnik, Stari Grad Fortress, and other beautiful spots.))){{{Top 3 Tourist Attractions in Bosnia and Herzegovina:}}}{{{{1. Skakavac Waterfall:}}}} (((Located 12 km north of Sarajevo, it's one of the highest waterfalls in Bosnia and Herzegovina at 98 meters, offering breathtaking views of green mountains and cascading waterfalls.))){{{{2. Neretva River:}}}} (((Passing through Konjic, it's the largest river in the eastern part of the Adriatic Sea, known for its beautiful natural scenery spread along its banks.))){{{{3. Jahorina Mountain:}}}} (((Near the municipality of Pale and bordering Trebevi Mountain, it's part of the Dinaric Alps. With its highest peak reaching 1910 meters, it's ideal for skiing and was the venue for the 1984 Winter Olympics. Accessible from Sarajevo by bus.)))"),
       ("https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/articles/articles-4.jpg",
        "Hotels", "Bosnia", "The best 3 hotels in Bosnia", "For those looking for the most important hotels in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "(((For those looking for the most important hotels in Bosnia, we present an overview of some hotels in Sarajevo:))) {{{Hollywood Hotel}}} (((Located 2 km from Sarajevo International Airport and near the Ferhadija Springs in Bosnia, a tributary of the Bosna River, Hollywood Hotel is situated in the Ilida area.))) (((It offers modern and spacious rooms with complimentary use of the indoor pool, sauna, and sports center.))) (((Hollywood Hotel features 18 conference and meeting rooms, 3 restaurants, and a supermarket is located just 100 meters from the hotel.))) {{{Malak Regency Hotel}}} (((Just 12 km from the capital Sarajevo, Malak Regency Hotel - a 5-star hotel - is located in the Ilida area with a charming view of the mountains.))) (((The hotel is only about 5 km away from Sarajevo International Airport.))) (((One of the distinguishing features of this hotel is that it does not serve alcoholic beverages.))) (((The hotel also features an indoor pool, sauna, fitness center, and a gift shop.))) (((Local and international cuisine is served at this hotel.))) {{{Radon Plaza Hotel}}} (((Radon Plaza Hotel is classified as a 5-star hotel and is distinguished by its proximity to Sarajevo Airport, just 2.8 km away.))) (((Its rooms are equipped with soundproofing systems, some of which are designated as suites for honeymooners.))) (((The hotel also includes a wellness center available for complimentary use.))) (((The hotel's restaurant, located on the 15th floor, offers panoramic views of the city and serves breakfast)))"),
       ("https://lll.ba/wp-content/uploads/2023/08/Old-Bridge-Stari-most-Unesco-Mostar-Bosnia-Herzegovina-lll.ba_-1.jpg",
        "tourism", "Bosnia", "An overview of tourism in Bosnia", "For those seeking vital tourism info in Bosnia.",
        "The Hotel Hollywood is a five-star hotel located in Ilida, a district of Sarajevo.", "available",
        "{{{Information about Bosnia and Herzegovina:}}}(((Bosnia and Herzegovina is characterized by its diverse attractions and tourist areas that attract tourists and visitors from different parts of the world to the extent that some websites describe it as one of the best tourist destinations in Europe due to its unique landmarks, charming nature, and affordable tourism prices compared to neighboring European countries.))){{{History of Bosnia and Herzegovina:}}}(((Bosnia is an ancient European country with a long history. It has enjoyed an important political and geographical status since the Middle Ages until the present day. It has been present on maps and known by its current name, Bosnia, for over 650 years, indicating its historical roots and antiquity.))){{{Location of Bosnia and Herzegovina:}}}(((The Republic of Bosnia and Herzegovina is located in the region known as the Balkans, situated in the southeastern part of Europe. Bosnia has a coastline on the Adriatic Sea, which is a branch of the Mediterranean Sea. The Adriatic Sea separates the Italian peninsula from the Balkan Peninsula, and the Dinaric Alps separate it from the Apennine Mountains.))){{{Weather in Bosnia and Herzegovina:}}} {{{{Bosnia is characterized by two main climates:}}}} {{{{{Continental or semi-continental climate:}}}}}(((The country experiences hot summers and cold winters, with snowfall. This climate is concentrated in the northern part of Bosnia and Herzegovina.))){{{{{Mediterranean climate:}}}}}(((This type of climate is evident in the southern part of Bosnia.)))");
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `message`)
VALUES ('John Doe', 'john@example.com', '1234567890', 'Great food and service!'),
       ('Jane Smith', 'jane@example.com', '0987654321', 'Lovely atmosphere, will definitely come back.'),
       ('Michael Johnson', 'michael@example.com', '9876543210', 'The staff was friendly and the food was delicious.'),
       ('Emily Brown', 'emily@example.com', '4567890123', 'Had a fantastic time, highly recommend!'),
       ('David Lee', 'david@example.com', '3210987654', 'Everything was perfect, thank you!');
INSERT INTO `users` (`name`, `password`, `email`, `img`, `DOB`, `phone`, `country`, `job_title`, `YOE`, `level`,
                     `gender`, `nationality`, `skills`, `ratings`)
VALUES ('Ibrahim Mohamed', '1234', 'I@b.n',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/avatar.png',
        '2004-12-18', '01110472777', 'Bosnia', 'Web', 1, 30, 'Male', 'Egyptian', 'Arabic HTML CSS JS Drive MySQL',
        '1 5 4 3 5 4 1 0 2 5'),
       ('Ahmed Nasser', 'password1', 'ahmed@example.com',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/friend-01.jpg',
        '2000-01-11', '+1234567890', 'Kuwait', 'Tourist', 1, 10, 'Male', 'Lebanese', 'Bosnian Driving English',
        '1 5 4 3 5 4 1 0 2 5'),
       ('Omar Fathy', 'password2', 'omar@example.com',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/friend-02.jpg',
        '2000-01-11', '+987654321', 'Egypt', 'Driver', 3, 20, 'Male', 'Jordanian', 'Arabic German Bosnian',
        '0 2 1 4 5'),
       ('Omar Ahmed', 'password3', 'omar.ahmed@example.com',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/friend-03.jpg',
        '2000-01-11', '+555555555', 'Qatar', 'Tourist Guide', 4, 3, 'Male', 'Emirati', 'English Driving German',
        '4 1 2 3 5'),
       ('Shady Nabil', 'password4', 'shady@example.com',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/friend-04.jpg',
        '2000-01-11', '+444444444', 'Syria', 'Translator', 5, 53, 'Male', 'Qatari', 'German Driving English',
        '5 4 1 0 2'),
       ('Mohamed Ibrahim', 'password5', 'mohamed@example.com',
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/friend-05.jpg',
        '2000-01-11', '+111111111', 'Iraq', 'Tourist', 6, 4, 'Male', 'Iraqi', 'Bosnian Reading Arabic', '3 1 2 0 4');
INSERT INTO carts (user_id)
VALUES (1),
       (2),
       (3),
       (4),
       (5);
INSERT INTO `coupon` (`max_times`, `code`, `amount`, `percentage`)
VALUES (5, 'SAVE50', 0, 0.15),
       (10, 'SALE20', 10, NULL),
       (3, 'FOODIE15', 0, 0.75);
INSERT INTO activities (user_id, img_src, name, description, date, time)
VALUES (1,
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/activity-01.png',
        'Store', 'Bought The Mastering JS Course', CURDATE() - INTERVAL 1 DAY, '18:10'),
       (1,
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/activity-02.png',
        'Academy', 'Got The PHP Certificate', CURDATE() - INTERVAL 1 DAY, '12:04'),
       (1,
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/activity-03.png',
        'Badges', 'Unlocked The 10 Skills Badge', '2021-02-10', '12:04'),
       (1,
        'https://raw.githubusercontent.com/IbrahimMoatazMohamed/IT-207-Introduction-to-Web-Programming/main/assets/images/profile/activity-01.png',
        'Store', 'Bought The Typescript Course', '2012-02-01', '12:04');
INSERT INTO tickets (user_id, label, icon, achieved)
VALUES (1, 'Rented cars', 'fa-car', 300),
       (1, 'Available Car', 'fa-car-tunnel', 5),
       (1, 'Tourists', 'fa-person', 600),
       (1, 'Tourist Group', 'fa-users-rays', 50);
INSERT INTO targets (user_id, label, goal, icon, achieved)
VALUES (1, 'Money', 20000.00, 'fa-euro-sign', 10000.00),
       (1, 'Tourist Group', 100.00, 'fa-users-rays', 30.00),
       (1, 'Project', 20.00, 'fa-bars-progress', 19.00);
INSERT INTO drafts (user_id, title, content, time)
VALUES (1, 'Check My Tasks List', 'Review the tasks list and update as needed.', '2022-10-26 12:00:00'),
       (1, 'Check My Projects', 'Review the project status and update tasks.', '2022-10-26 12:30:00'),
       (1, 'Call All My Clients', 'Call all clients to discuss project progress.', '2022-10-26 13:00:00'),
       (1, 'Finish The Development Workshop', 'Finalize the development workshop content.', '2022-10-26 13:30:00');
INSERT INTO `password_history` (`user_id`, `change_date`)
VALUES (1, '2023-04-25 10:00:00'),
       (1, CURRENT_TIMESTAMP),
       (1, '2021-04-24 15:30:00');
INSERT INTO `widgets` (`user_id`)
VALUES (1),
       (2),
       (3),
       (4),
       (5);
